language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.7"
before_install:
  - sudo apt-get update
  # install library dependencies
  - sudo apt-get install libzbar0 make perl
  # Install exiftool
  - wget https://exiftool.org/Image-ExifTool-12.01.tar.gz
  - tar -xzf Image-ExifTool-12.01.tar.gz 
  - pushd Image-ExifTool-12.01/
  - perl Makefile.PL 
  - make test
  - sudo make install
  - popd
install:
  # Now install miniconda
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Finally create conda environment and run tests
  - conda env create -f micasense_conda_env.yml
  - conda activate micasense

script:
  # Your test script goes here
  - pytest -n auto .
